{{-- This view file shows part of the interface and is kept simple so it is easy to follow. --}}
@props([
    'id' => 'editorjs-data',
    'size' => 'size-full',
    'editordata' => null,
])

@php
    $holderId = $id . '-editor';
    $inputId = $id . '-data';

    $editorClasses = [
        $size,
        'font-normal',
        'p-2',
        'bg-zinc-100',
        'rounded-sm',
        'shadow-sm',
        'text-black',
        'focus:outline-0',
        'text-left',
        'overflow-x-hidden',
        'overflow-y-auto',
    ];

    $editorAttributes = $attributes->except(['id', 'class'])->merge([
        'class' => implode(' ', $editorClasses),
        'data-editor-holder' => $holderId,
        'data-editor-input' => $inputId,
    ]);

    $editorDataHTMLSafe = $editordata;

    // Prefer raw JSON first to avoid unnecessary entity transformations (e.g. links/query params).
    if ($editordata) {
        $decodedData = json_decode($editordata, true);

        // Fallback for legacy HTML-entity encoded payloads.
        if (!is_array($decodedData)) {
            $decodedData = json_decode(html_entity_decode($editordata, ENT_QUOTES, 'UTF-8'), true);
        }

        $editordata = is_array($decodedData) ? $decodedData : null;
    }
@endphp

@push('scripts')
    <script>
        window.editorDataRegistry = window.editorDataRegistry || {};
        window.editorDataRegistry[@json($holderId)] = @json($editordata);
    </script>
    @vite('resources/js/editor/editorjs.js')
@endpush

@push('styles')
    {{-- Global text editor styles --}}
    <style>
        .cdx-block{
            padding: 0;
        }

        .ce-paragraph{
            line-height: 1.25em;
        }

        .cdx-marker{
            background: yellow !important;
        }
    </style>
@endpush

{{-- Hidden input field --}}
<input type="hidden" id="{{$inputId}}" name="{{$id}}" {{$editorAttributes['required'] ? 'required' : ''}} value="{{$editorDataHTMLSafe}}" />

{{-- Editor input --}}
<div id="{{$holderId}}" {{$editorAttributes->except(['value'])}} style="position:relative"></div>

{{-- Visible fallback image button (small) placed in the top-right of the editor holder so admins can open the file picker if the toolbox injection fails. --}}
<button type="button" aria-label="Insert image" title="Image" onclick="document.getElementById('@js($holderId)-image-input').click()" style="position:relative; margin-top:4px; display:inline-block;">
    <span style="display:inline-block; padding:4px 6px; background:#111827; color:white; border-radius:6px; font-size:12px;">Image</span>
</button>

{{-- Hidden file input and status used when admin clicks the EditorJS "+" control --}}
<input id="{{$holderId}}-image-input" type="file" accept="image/*" class="hidden" />
<span id="{{$holderId}}-image-status" class="text-sm text-zinc-500 hidden"></span>

@push('scripts')
    <script>
        document.addEventListener('DOMContentLoaded', function(){
            const holderId = @json($holderId);
            const input = document.getElementById(holderId + '-image-input');
            const status = document.getElementById(holderId + '-image-status');

            if (!input) return;

            // When admin clicks the EditorJS "+" control within this editor, open the file picker.
            document.addEventListener('click', function (ev) {
                const target = ev.target;

                // Find the editor holder ancestor for the clicked element, if any
                const clickedHolder = target.closest('[data-editor-holder]');
                if (!clickedHolder) return;
                if (clickedHolder.getAttribute('data-editor-holder') !== holderId) return;

                // Detect common plus/button controls generated by EditorJS or toolboxes.
                const isPlus = target.classList?.contains('cdx-plus')
                    || target.classList?.contains('ce-block__plus')
                    || target.classList?.contains('ce-action__plus')
                    || target.getAttribute('title') === 'Add'
                    || target.textContent?.trim() === '+';

                if (!isPlus) return;

                // Open the hidden file input for this editor instance
                input.click();
            });

            // Also inject an "Image" item into the EditorJS insert toolbox when it appears so users
            // can explicitly choose Image from the menu without rebuilding frontend assets.
            const tryInjectImageItem = () => {
                // Look for any toolbox/palette that contains the standard tool labels (Text, Heading, Table...)
                const candidates = Array.from(document.querySelectorAll('div, ul'));
                for (const el of candidates) {
                    const text = (el.textContent || '').trim();
                    if (!text) continue;

                    // crude heuristic: toolbox contains the word 'Heading' and 'Text'
                    if (text.includes('Heading') && text.includes('Text')) {
                        // if our image item already exists, stop
                        if (el.querySelector('.zijpalm-image-tool')) return;

                        // Create a simple item similar to editor items
                        const item = document.createElement('div');
                        item.className = 'zijpalm-image-tool cursor-pointer py-1 px-2 text-sm text-left';
                        item.style.display = 'flex';
                        item.style.alignItems = 'center';
                        item.style.gap = '0.5rem';
                        item.innerHTML = '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="24" height="24" rx="2" fill="#E5E7EB"></rect><path d="M6 15l2-2 3 3 4-4 4 4v1H6v-2z" fill="#374151"></path></svg><span>Image</span>';

                        item.addEventListener('click', (ev) => {
                            ev.stopPropagation();
                            input.click();
                        });

                        // Append to toolbox element (if it's a list or div)
                        el.appendChild(item);
                        return;
                    }
                }
            };

            // Observe DOM mutations to inject when the toolbox appears
            const observer = new MutationObserver((mutations) => {
                tryInjectImageItem();
            });
            observer.observe(document.body, { childList: true, subtree: true });

            input.addEventListener('change', async (e) => {
                const file = e.target.files && e.target.files[0];
                if (!file) return;

                // Basic client-side validation
                if (file.size > 5 * 1024 * 1024) { // 5MB
                    status.textContent = 'Bestand is te groot (max 5MB).';
                    return;
                }

                    status.textContent = 'Uploaden...';
                    status.classList.remove('hidden');

                const fd = new FormData();
                fd.append('image', file);

                try {
                    const resp = await fetch('/admin/editor/image-upload', {
                        method: 'POST',
                        credentials: 'same-origin',
                        body: fd,
                        headers: {
                            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                        }
                    });

                    if (!resp.ok) {
                        throw new Error('Upload failed: ' + resp.statusText);
                    }

                    const data = await resp.json();
                    const url = data.url;

                    // Insert image into the editor. Prefer a proper image block if the Image tool is registered,
                    // otherwise fall back to inserting centered HTML which the mail sanitizer will allow.
                    const holderEl = document.querySelector('[data-editor-holder="' + holderId + '"]');
                    const editable = holderEl?.querySelector('[contenteditable="true"]');

                    const centeredHtml = '<center><img src="' + url + '" alt="Afbeelding" style="max-width:600px;width:100%;height:auto;display:block;margin:0 auto;"/></center>';

                    // Try EditorJS block insertion (image tool). Different image tools expect different payload shapes,
                    // attempt a few common ones.
                    try {
                        if (holderEl?.editorInstance && holderEl.editorInstance.blocks) {
                            // Try the most common shapes used by editorjs-image
                            try { holderEl.editorInstance.blocks.insert('image', { file: { url } }); status.textContent = 'Upload geslaagd'; return; } catch (e) {}
                            try { holderEl.editorInstance.blocks.insert('image', { data: { url } }); status.textContent = 'Upload geslaagd'; return; } catch (e) {}
                            // If insertion by block type fails, try inserting raw HTML into the editable area
                        }
                    } catch (err) {
                        // ignore and fall back
                    }

                    if (editable && document.queryCommandSupported && document.queryCommandSupported('insertHTML')) {
                        editable.focus();
                        document.execCommand('insertHTML', false, centeredHtml);
                    } else if (holderEl?.editorInstance) {
                        try {
                            holderEl.editorInstance.blocks.insert('paragraph', { text: centeredHtml });
                        } catch (err) {
                            // ignore
                        }
                    }

                    // Trigger save to update the hidden input
                    try { holderEl?.editorInstance?.save().then((output)=>{ /* no-op */ }); } catch (err) {}

                    status.textContent = 'Upload geslaagd';
                    status.classList.remove('hidden');
                } catch (err) {
                    console.error(err);
                    status.textContent = 'Upload mislukt';
                    status.classList.remove('hidden');
                }
            });
        });
    </script>
@endpush

